#!/usr/bin/env python3
"""
Demo script to show Streamlit app information
"""

print("SURAKSHA ANALYTICS - STREAMLIT WEB APP")
print("=" * 50)
print()
print("To run the Streamlit web application:")
print()
print("Option 1 - Using the runner script:")
print("   python run_streamlit.py")
print()
print("Option 2 - Direct Streamlit command:")
print("   streamlit run streamlit_app.py")
print()
print("Option 3 - With custom port:")
print("   streamlit run streamlit_app.py --server.port 8502")
print()
print("The app will open in your browser at:")
print("   http://localhost:8501")
print()
print("Features you'll get with Streamlit:")
print("   * Interactive dropdowns for selections")
print("   * Embedded plots and charts")
print("   * Professional web interface")
print("   * Mobile-friendly responsive design")
print("   * Real-time updates")
print("   * Interactive data tables")
print("   * Tabbed analysis sections")
print()
print("Comparison with CLI version:")
print("   CLI Version        ->  Streamlit Version")
print("   Text input         ->  Dropdown menus")
print("   Console output     ->  Web interface")
print("   Pop-up plots       ->  Embedded charts")
print("   Sequential steps   ->  Tab navigation")
print()
print("Requirements:")
print("   * All packages from requirements.txt")
print("   * Same Dataset folder with CSV files")
print("   * Web browser for viewing")
print()
print("Both versions use the same analysis logic!")
print("=" * 50)